- name: satellite-registration
  hosts: all
  become: yes

  tasks:

   - name: Uptime checking
     command: uptime
     register: out
   - debug: msg="{{ out.stdout }}"
   
   - name: create file
     file: path=/tmp/nologin state=touch
     ignore_errors: yes
     register: va
   - debug: msg="{{ va.stdout }}"
