- name: satellite-registration
  hosts: all
  become: yes

  tasks:

   - name: Uptime checking
     command: uptime > /tmp/test/uname; uname -r >> /tmp/test/uname
     register: out
   - debug: msg="{{ out.stdout }}"
