- name: satellite-registration
  hosts: all
  become: yes

  tasks:

   - name: Uptime checking
     command: uptime; df -h
     register: out
   - debug: msg="{{ out.stdout }}"
   
   - name: create file
     file: path=/tmp/vinothfile state=touch
     
   - name: trivially create a file
     shell: echo "hello" > /tmp/hello
     args:
       creates: /tmp/hello

