- name: satellite-registration
  hosts: all

  tasks:

   - name: Uptime checking
     shell: uptime > /home/awx/uptime; uname -r > /home/awx/uname
     register: out
   - debug: msg="{{ out.stdout }}"
