- name: satellite-registration
  hosts: all
  become: yes

  tasks:

   - name: Uptime checking
     shell: uptime > /tmp/uptime.txt; uname -r > /tmp/uname.txt
     register: out
   - debug: msg="{{ out.stdout }}"
