- name: satellite-registration
  hosts: all
  become: yes

  tasks:

   - name: Uptime checking
     command: uptime
     register: out
   - debug: msg="{{ out.stdout }}"
   
   - name: create file
     shell: touch /tmp/123vino
     warn: false
     register: va
   - debug: msg="{{ va.stdout }}"
